// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SecondRave.proto

package com.secondrave.protos;

public final class SecondRaveProtos {
  private SecondRaveProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AudioPieceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:secondraveprotos.AudioPiece)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 playAt = 1;</code>
     */
    boolean hasPlayAt();
    /**
     * <code>required int64 playAt = 1;</code>
     */
    long getPlayAt();

    /**
     * <code>required int32 duration = 2;</code>
     */
    boolean hasDuration();
    /**
     * <code>required int32 duration = 2;</code>
     */
    int getDuration();

    /**
     * <code>required bytes audioData = 3;</code>
     */
    boolean hasAudioData();
    /**
     * <code>required bytes audioData = 3;</code>
     */
    com.google.protobuf.ByteString getAudioData();
  }
  /**
   * Protobuf type {@code secondraveprotos.AudioPiece}
   */
  public static final class AudioPiece extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:secondraveprotos.AudioPiece)
      AudioPieceOrBuilder {
    // Use AudioPiece.newBuilder() to construct.
    private AudioPiece(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AudioPiece(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AudioPiece defaultInstance;
    public static AudioPiece getDefaultInstance() {
      return defaultInstance;
    }

    public AudioPiece getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AudioPiece(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              playAt_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              duration_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              audioData_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.secondrave.protos.SecondRaveProtos.internal_static_secondraveprotos_AudioPiece_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.secondrave.protos.SecondRaveProtos.internal_static_secondraveprotos_AudioPiece_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.secondrave.protos.SecondRaveProtos.AudioPiece.class, com.secondrave.protos.SecondRaveProtos.AudioPiece.Builder.class);
    }

    public static com.google.protobuf.Parser<AudioPiece> PARSER =
        new com.google.protobuf.AbstractParser<AudioPiece>() {
      public AudioPiece parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AudioPiece(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<AudioPiece> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int PLAYAT_FIELD_NUMBER = 1;
    private long playAt_;
    /**
     * <code>required int64 playAt = 1;</code>
     */
    public boolean hasPlayAt() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 playAt = 1;</code>
     */
    public long getPlayAt() {
      return playAt_;
    }

    public static final int DURATION_FIELD_NUMBER = 2;
    private int duration_;
    /**
     * <code>required int32 duration = 2;</code>
     */
    public boolean hasDuration() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 duration = 2;</code>
     */
    public int getDuration() {
      return duration_;
    }

    public static final int AUDIODATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString audioData_;
    /**
     * <code>required bytes audioData = 3;</code>
     */
    public boolean hasAudioData() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes audioData = 3;</code>
     */
    public com.google.protobuf.ByteString getAudioData() {
      return audioData_;
    }

    private void initFields() {
      playAt_ = 0L;
      duration_ = 0;
      audioData_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPlayAt()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDuration()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAudioData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, playAt_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, duration_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, audioData_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, playAt_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, duration_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, audioData_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.secondrave.protos.SecondRaveProtos.AudioPiece parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.secondrave.protos.SecondRaveProtos.AudioPiece parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.secondrave.protos.SecondRaveProtos.AudioPiece parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.secondrave.protos.SecondRaveProtos.AudioPiece parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.secondrave.protos.SecondRaveProtos.AudioPiece parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.secondrave.protos.SecondRaveProtos.AudioPiece parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.secondrave.protos.SecondRaveProtos.AudioPiece parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.secondrave.protos.SecondRaveProtos.AudioPiece parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.secondrave.protos.SecondRaveProtos.AudioPiece parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.secondrave.protos.SecondRaveProtos.AudioPiece parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.secondrave.protos.SecondRaveProtos.AudioPiece prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code secondraveprotos.AudioPiece}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:secondraveprotos.AudioPiece)
        com.secondrave.protos.SecondRaveProtos.AudioPieceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.secondrave.protos.SecondRaveProtos.internal_static_secondraveprotos_AudioPiece_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.secondrave.protos.SecondRaveProtos.internal_static_secondraveprotos_AudioPiece_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.secondrave.protos.SecondRaveProtos.AudioPiece.class, com.secondrave.protos.SecondRaveProtos.AudioPiece.Builder.class);
      }

      // Construct using com.secondrave.protos.SecondRaveProtos.AudioPiece.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        playAt_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        duration_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        audioData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.secondrave.protos.SecondRaveProtos.internal_static_secondraveprotos_AudioPiece_descriptor;
      }

      public com.secondrave.protos.SecondRaveProtos.AudioPiece getDefaultInstanceForType() {
        return com.secondrave.protos.SecondRaveProtos.AudioPiece.getDefaultInstance();
      }

      public com.secondrave.protos.SecondRaveProtos.AudioPiece build() {
        com.secondrave.protos.SecondRaveProtos.AudioPiece result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.secondrave.protos.SecondRaveProtos.AudioPiece buildPartial() {
        com.secondrave.protos.SecondRaveProtos.AudioPiece result = new com.secondrave.protos.SecondRaveProtos.AudioPiece(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.playAt_ = playAt_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.duration_ = duration_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.audioData_ = audioData_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.secondrave.protos.SecondRaveProtos.AudioPiece) {
          return mergeFrom((com.secondrave.protos.SecondRaveProtos.AudioPiece)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.secondrave.protos.SecondRaveProtos.AudioPiece other) {
        if (other == com.secondrave.protos.SecondRaveProtos.AudioPiece.getDefaultInstance()) return this;
        if (other.hasPlayAt()) {
          setPlayAt(other.getPlayAt());
        }
        if (other.hasDuration()) {
          setDuration(other.getDuration());
        }
        if (other.hasAudioData()) {
          setAudioData(other.getAudioData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPlayAt()) {

          return false;
        }
        if (!hasDuration()) {

          return false;
        }
        if (!hasAudioData()) {

          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.secondrave.protos.SecondRaveProtos.AudioPiece parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.secondrave.protos.SecondRaveProtos.AudioPiece) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long playAt_ ;
      /**
       * <code>required int64 playAt = 1;</code>
       */
      public boolean hasPlayAt() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 playAt = 1;</code>
       */
      public long getPlayAt() {
        return playAt_;
      }
      /**
       * <code>required int64 playAt = 1;</code>
       */
      public Builder setPlayAt(long value) {
        bitField0_ |= 0x00000001;
        playAt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 playAt = 1;</code>
       */
      public Builder clearPlayAt() {
        bitField0_ = (bitField0_ & ~0x00000001);
        playAt_ = 0L;
        onChanged();
        return this;
      }

      private int duration_ ;
      /**
       * <code>required int32 duration = 2;</code>
       */
      public boolean hasDuration() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 duration = 2;</code>
       */
      public int getDuration() {
        return duration_;
      }
      /**
       * <code>required int32 duration = 2;</code>
       */
      public Builder setDuration(int value) {
        bitField0_ |= 0x00000002;
        duration_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 duration = 2;</code>
       */
      public Builder clearDuration() {
        bitField0_ = (bitField0_ & ~0x00000002);
        duration_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString audioData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes audioData = 3;</code>
       */
      public boolean hasAudioData() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes audioData = 3;</code>
       */
      public com.google.protobuf.ByteString getAudioData() {
        return audioData_;
      }
      /**
       * <code>required bytes audioData = 3;</code>
       */
      public Builder setAudioData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        audioData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes audioData = 3;</code>
       */
      public Builder clearAudioData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        audioData_ = getDefaultInstance().getAudioData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:secondraveprotos.AudioPiece)
    }

    static {
      defaultInstance = new AudioPiece(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:secondraveprotos.AudioPiece)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_secondraveprotos_AudioPiece_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_secondraveprotos_AudioPiece_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020SecondRave.proto\022\020secondraveprotos\"A\n\n" +
      "AudioPiece\022\016\n\006playAt\030\001 \002(\003\022\020\n\010duration\030\002" +
      " \002(\005\022\021\n\taudioData\030\003 \002(\014B)\n\025com.secondrav" +
      "e.protosB\020SecondRaveProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_secondraveprotos_AudioPiece_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_secondraveprotos_AudioPiece_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_secondraveprotos_AudioPiece_descriptor,
        new String[] { "PlayAt", "Duration", "AudioData", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
